{{- if and .Values.kubernetesRunner.sharedPvc.enabled (not .Values.kubernetesRunner.sharedPvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dm-sql-to-falkordb.runnerSharedPvcName" . }}
  namespace: {{ include "dm-sql-to-falkordb.runnerNamespace" . }}
  labels:
    {{- include "dm-sql-to-falkordb.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.kubernetesRunner.sharedPvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.kubernetesRunner.sharedPvc.size }}
  {{- if .Values.kubernetesRunner.sharedPvc.storageClassName }}
  storageClassName: {{ .Values.kubernetesRunner.sharedPvc.storageClassName }}
  {{- end }}
{{- end }}
